site_name: MooGoo's Documentations

nav:
  - Home: index.md
  - Tech:
    - snippets: tech/snippets.md
    - Unix/Linux: tech/unix-linux.md
    - Server: tech/server.md
    - OS/Desktop: tech/os.md
    - Tools:
      - Git: tech/git.md
      - Docker: tech/docker.md
    - Programming Language:
      - JavaScript: tech/javascript.md
    - Database:
      - PostgreSQL: tech/postgresql.md
      - SQLite: tech/sqlite.md
  - Blog:
    - blog/index.md

theme:
  name: 'material'
  #custom_dir: overrides
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
  palette:
    - scheme: slate
      primary: light blue
      accent: yellow
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - blog:
      post_dir: "{blog}/articles"
      post_date_format: yyyy.MM.dd
      post_url_date_format: yyyy-MM-dd
      post_readtime: false
      post_excerpt_separator: <!-- more -->
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-T9S48WVHD5
#extra_css:
#  - stylesheets/extra.css