site_name: MooGoo Knowledge Management

nav:
  - Tech:
    - Database:
      - PostgreSQL: tech/postgresql.md
      - SQLite: tech/sqlite.md
    - Git: tech/git.md
    - Docker: tech/docker.md
    - Unix/Linux: tech/unix-linux.md
    - AWS: tech/aws.md

theme:
  name: 'material'
  custom_dir: overrides
  features:
    - content.code.copy

plugins:
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-T9S48WVHD5
