site_name: MooGoo's Documentations

nav:
  - About:
    - index: index.md
    - Tags: tags.md
  - Tech:
    - snippets: tech/snippets.md
    - Security: tech/security.md
    - Persistant Identifier: tech/pid.md
    - GIS: tech/gis.md
    - Systems, Platforms, Services, Shell:
      - Unix/Linux Commands: tech/unix-linux-command.md
      - Powershell: tech/powershell.md
      - Server: tech/server.md
      - OS/Desktop: tech/os.md
      - System Degsin/Architecture: tech/arch.md
      - AWS: tech/aws.md
    - Tools:
      - Git: tech/git.md
      - tmux: tech/tmux.md
      - Docker: tech/docker.md
      - Emacs: tech/emacs.md
      - Mkdocs-material: tech/mkdocs-material.md
    - Programming Language:
      - Python: tech/python.md
      - JavaScript: tech/javascript.md
      - Other(LISP): tech/other-lang.md
    - Database:
      - Database: tech/database.md
      - SQL Syntax: tech/sql_syntax.md
      - PostgreSQL: tech/postgresql.md
      - MySQL: tech/mysql.md
      - SQLite: tech/sqlite.md
      - DuckDB: tech/duckdb.md
      - Redis: tech/redis.md
    - Application:
      - Data Visualization: tech/data-viz.md
      - Service: tech/service.md
    - Design:
      - Desgin: tech/design.md
      - Web Design: tech/web_design.md
      - Resources: tech/web_design_resources.md
      - Gallery: tech/web_design_gallery.md
  - Music:
    - music/about.md
    - music/songs.md
    - music/kindergarten.md
  - Nature:
    - nature/field-guide.md
    - nature/taiwan.md
    - 物種:
      - 動物:
        - nature/taxon-mammal.md
        - nature/taxon-spider.md
        - nature/taxon-gryllidae.md
        - nature/taxon-blattodea.md
        - nature/taxon-centipede-and-millipede.md
        - nature/taxon-snake.md
        - nature/taxon-horseshoe-crab.md
        - nature/taxon-coral.md
      - 植物:
        - nature/taxon-seagrass.md
    - nature/animal-rescue.md
    - nature/invasive.md
    - nature/animal-behavior.md
    - nature/geologic-time-scale.md
  - Life:
    - life/housing.md
  - Web:
    - web/index.md
  - Blog:
    - blog/index.md

theme:
  name: 'material'
  #custom_dir: overrides
  favicon: images/favicon.ico
  features:
    - content.code.copy
    - navigation.tabs
    #- navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
  #palette:
  #  - scheme: slate
  #    primary: light blue
  #    accent: yellow
  font:
    text: Roboto
    code: Roboto Mono
  #icon:
  #  tag:
  #    html: fontawesome/brands/html5
  #    js: fontawesome/brands/js
  #    css:  fontawesome/brands/css3

plugins:
  - blog:
      post_dir: "{blog}/articles"
      post_url_format: "{file}"
      post_date_format: yyyy.MM.dd
      post_url_date_format: yyyy-MM-dd
      post_readtime: false
      post_excerpt_separator: <!-- more -->
  - search
  - tags:
      tags_file: tags.md

extra:
  analytics:
    provider: google
    property: G-T9S48WVHD5
  tags:
    museum: museum
    #extra_css:
#  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.keys
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
