site_name: MooGoo Knowledge Management
nav:
  - Database:
    - PostgreSQL: database/postgresql.md
    - SQLite: database/sqlite.md
theme:
  name: 'material'
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-T9S48WVHD5